name: CI/CD Workflow

on:
  push:
    branches:
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check files in working directory
        run: ls -la ${{ github.workspace }}
        working-directory: ${{ github.workspace }}

      - name: Install dependencies
        run: composer require phpunit/phpunit
        working-directory: ${{ github.workspace }}

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check files in working directory
        run: ls -la ${{ github.workspace }}
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: ${{ github.workspace }}/vendor/bin/phpunit tests --coverage-html coverage
        working-directory: ${{ github.workspace }}
