name: CI/CD Workflow
on:
  push:
    branches:
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: composer i
        working-directory: ${{ github.workspace }}

  # Tests
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Test
        run: ./vendor/bin/phpunit tests --coverage-html coverage
        working-directory: ${{ github.workspace }}